### ISSUE TITLE
Rename XDA.html to listing.html, and XDA.css to listing.css

### ISSUE THREAD

**Issue by jacksonhvisuals** [xda/XDA-Labs-Store-UI#15]
It's not named right now that we have multiple pages, all for XDA stuff.

**Comment by corcoran** [comment]
Yea we'll need to update this in the backend too, I'll handle it.

I think we should call it details.html or app.html though

**Comment by jacksonhvisuals** [comment]
Sure.

**Comment by jacksonhvisuals** [comment]
Hopefully I didn't break anything with https://github.com/xda/XDA-Labs-Store-UI/commit/e827830b7855c993a94e1953bb935b33ef00cabf 😁
