### ISSUE TITLE
Replace inline styles with CSS classes

### ISSUE THREAD

**Issue by corcoran** [xda/XDA-Labs-Store-UI#17]
We need to create proper CSS classes for every component/section of index/details and remove most if not all inline styles

**Comment by corcoran** [comment]
I've cleaned up a few element (the ones we iterate through in loops, etc) but we really should migrate all the inline styles and properly use our external css files

**Comment by jacksonhvisuals** [comment]
Finished this, I think, with https://github.com/xda/XDA-Labs-Store-UI/commit/e644545f3e8505a61c89505211f234cae06eb537

**Comment by jacksonhvisuals** [comment]
Er, need to do header.

**Comment by jacksonhvisuals** [comment]
Finished this, I think.
