### ISSUE TITLE
Extract footer into separate file, include in both details and index pages

### ISSUE THREAD

**Issue by corcoran** [xda/XDA-Labs-Store-UI#18]
We should also update the footer to include
1) XDA copyright
2) A link to the source (Github)
3) A link to the main page (portal)

**Comment by jacksonhvisuals** [comment]
What kind of look are you going for for the footer links?

**Comment by corcoran** [comment]
-------------------------
XDA Labs, an [XDA Developers](http://www.xda-developers.com) platform.  [Tell me more!](http://www.xda-developers.com/xda-labs)       [right aligned => (GITHUB ICON linking to https://github.com/xda/XDA-Labs-Store-UI)]
Copyright © 2017 xda-developers
-------------------------
text color #AAA link color weight 400 #FFF

**Comment by jacksonhvisuals** [comment]
Done, AFAIK.
