### ISSUE TITLE
ERR_CONNECTION_RESET when trying to add new build

### ISSUE THREAD

**Issue by csagan5** [xda/XDA-Labs-Store-UI#41]
When trying to add a build I get from Chrome:
```
This site can’t be reached

The connection was reset.
Try:
Checking the connection
Checking the proxy and the firewall
ERR_CONNECTION_RESET
```

The file is a 143MB .apk, and this is what I can see through developer tools:
```
Request URL:https://labs.xda-developers.com/manage/build/add/783dbd77-ba47-4aac-9051-8419dc04c9ac
Referrer Policy:no-referrer-when-downgrade
Request Headers
Provisional headers are shown
Content-Type:multipart/form-data; boundary=----WebKitFormBoundaryKIYHzeAS04b8MZPc
Origin:https://labs.xda-developers.com
Upgrade-Insecure-Requests:1
User-Agent:Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/62.0.3202.62 Safari/537.36
X-DevTools-Emulate-Network-Conditions-Client-Id:a0184a58-49d8-4527-a3fc-69010403fb2a
```

Perhaps you have a limit on file upload size? Also, on another note, my app has different .apk for different Android version and architecture, how would that work?

**Comment by corcoran** [comment]
Can you jump on telegram and send me your apk so I can test?  This isn't the place for these issues, this is the web console for the store, not the dev console (it currently doesn't have a public github).

**Comment by csagan5** [comment]
@corcoran ok, I see. I don't have telegram installed at the moment, you can try with any large .apk from here: https://github.com/bromite/bromite/releases (didn't try with smaller ones though)
