### ISSUE TITLE
Two two cards aren't max width under some resolutions

### ISSUE THREAD

**Issue by corcoran** [xda/XDA-Labs-Store-UI#8]
![image](https://user-images.githubusercontent.com/1402817/28648830-a1f4e7c4-723e-11e7-90e9-81cf955eb40d.png)

**Comment by jacksonhvisuals** [comment]
Yep, I noticed that. At some point in the transition from my own hosted
demo page to the Django backend/template mode, something got bumped. Will
look into this tomorrow.

**Comment by jacksonhvisuals** [comment]
Dang. I'm really having trouble pinpointing the issue... I tried replacing the first column's code entirely with something simple, but it still resized. Tried removing containers, columns, resizing columns, etc, but it keeps having the issue.

**Comment by jacksonhvisuals** [comment]
The funny thing is, the chrome web dev tools aren't showing any kind of padding or margin on the right. The only element that reflects this weird UI bug in the dimension/positioning window is the navbar... which makes no sense at all... 
![screen shot 2017-07-27 at 9 25 12 am](https://user-images.githubusercontent.com/29767267/28681204-8a02cf0e-72ad-11e7-8966-dc19370dad96.png)
